"""
    _bibtex_escape(s) -> String

Escape the traditional BibTeX metacharacters (`&`, `%`, `\$`, `#`, `_`, `{`,
`}`, `\\`). Unicode passes through untouched — modern engines (biber + biblatex,
or XeLaTeX) handle it natively, and escaping accented characters to TeX
commands would just hurt readability.
"""
function _bibtex_escape(s::AbstractString)
    out = IOBuffer()
    for c in s
        if c == '\\'
            print(out, "\\textbackslash{}")
        elseif c in ('&', '%', '\$', '#', '_', '{', '}')
            print(out, '\\', c)
        else
            print(out, c)
        end
    end
    return String(take!(out))
end

# last-whitespace-token of an author string, ASCII-sanitized.
# "Hans-Peter Müller" -> "Mller"  (strips non-ASCII-letters)
function _surname_ascii(name::AbstractString)
    parts = split(strip(String(name)))
    isempty(parts) && return ""
    return replace(String(last(parts)), r"[^A-Za-z0-9]" => "")
end

"""
    _bibtex_key(md) -> String

Deterministic `FirstAuthorSurname + Year` citekey. Falls back to a sanitized
form of the record key when no authors are known, and to `"nodate"` when year
is missing. Duplicate keys are disambiguated by [`write_bibtex`](@ref) with a
trailing letter suffix.
"""
function _bibtex_key(md::AbstractDict)
    y = get(md, "year", "")
    year_str = y isa Integer ? string(y) : String(y)
    isempty(year_str) && (year_str = "nodate")

    surname = ""
    authors = get(md, "authors", String[])
    if authors isa AbstractVector
        for a in authors
            s = _surname_ascii(String(a))
            if !isempty(s)
                surname = s
                break
            end
        end
    end
    if isempty(surname)
        fallback = replace(String(get(md, "key", "unknown")), r"[^A-Za-z0-9]" => "")
        surname = length(fallback) > 20 ? fallback[1:20] : fallback
        isempty(surname) && (surname = "unknown")
    end
    return string(surname, year_str)
end

"""
    bibtex_entry(md; key = _bibtex_key(md)) -> String

Render one metadata dict as a BibTeX entry string (including trailing newline).
Uses `@article` when `md["journal"]` is non-empty, `@misc` otherwise (arXiv
preprints, tech reports). Fields are always written in the same order.
"""
function bibtex_entry(md::AbstractDict; key::AbstractString=_bibtex_key(md))
    journal = String(get(md, "journal", ""))
    is_preprint = isempty(journal)
    entry_type = is_preprint ? "misc" : "article"

    io = IOBuffer()
    print(io, "@", entry_type, "{", key, ",\n")

    authors = get(md, "authors", String[])
    if authors isa AbstractVector && !isempty(authors)
        names = _bibtex_escape.(String.(authors))
        println(io, "  author  = {", join(names, " and "), "},")
    end

    title = String(get(md, "title", ""))
    isempty(title) || println(io, "  title   = {", _bibtex_escape(title), "},")

    isempty(journal) || println(io, "  journal = {", _bibtex_escape(journal), "},")

    y = get(md, "year", "")
    year_str = y isa Integer ? string(y) : String(y)
    isempty(year_str) || println(io, "  year    = {", year_str, "},")

    raw_key = String(get(md, "key", ""))
    doi = is_doi(raw_key) ? raw_key : String(get(md, "doi", ""))
    if !isempty(doi)
        println(io, "  doi     = {", doi, "},")
        println(io, "  url     = {https://doi.org/", doi, "},")
    end

    arxiv_id = String(get(md, "arxiv_id", ""))
    if isempty(arxiv_id) && startswith(raw_key, "arxiv:")
        arxiv_id = raw_key[7:end]
    end
    if !isempty(arxiv_id)
        println(io, "  eprint  = {", arxiv_id, "},")
        println(io, "  archivePrefix = {arXiv},")
    end

    print(io, "}\n")
    return String(take!(io))
end

"""
    write_bibtex(store, path; key_filter = nothing) -> Int

Iterate every `status = "ok"` entry in the store's `.metadata/`, assign a
`FirstAuthorSurnameYear` citekey (with letter-suffix disambiguation for
collisions), and write the combined BibTeX to `path`. Returns the number of
entries written. When `key_filter` is a `Set{String}` of normalized keys only
those entries are written.
"""
function write_bibtex(
    store::Store,
    path::AbstractString;
    key_filter::Union{Set{String},Nothing}=nothing,
)
    mkpath(dirname(path))
    n = 0
    used = Dict{String,Int}()

    open(path, "w") do io
        println(io, "% BibTeX file generated by BiblioFetch — edits will be overwritten.")
        for safekey in list_entries(store)
            p = joinpath(store.root, METADATA_DIRNAME, safekey * ".toml")
            isfile(p) || continue
            md = TOML.parsefile(p)
            get(md, "status", "") == "ok" || continue
            if key_filter !== nothing
                entry_key = String(get(md, "key", ""))
                entry_key in key_filter || continue
            end

            base = _bibtex_key(md)
            seen = get(used, base, 0)
            used[base] = seen + 1
            key = seen == 0 ? base : string(base, Char('a' + seen - 1))

            println(io, bibtex_entry(md; key=key))
            n += 1
        end
    end
    return n
end
